## 1. Accessing the data in the JSON

In [1]:
import pandas as pd
import requests
import os
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

True

In [12]:
# Get the weather for 5 days for Berlin.
# First define the latitude, longitude and API_key.
latitude = 52.5200
longitude = 13.405
API_key = os.getenv("API_key")
if API_key is None:
    print("Error: API_key not found in .env file!")
else:
    print(f"Key loaded successfully: {API_key[:5]}...") # prints first 5 characters

# Combine the different parts from above to create one url.
weather = requests.get(f"https://api.openweathermap.org/data/2.5/forecast?lat={latitude}&lon={longitude}&appid={API_key}", timeout=5)
weather_json = weather.json()
weather_json

Key loaded successfully: 50d72...

{'cod': '200',
 'message': 0,
 'cnt': 40,
 'list': [{'dt': 1772550000,
   'main': {'temp': 289.33,
    'feels_like': 288.34,
    'temp_min': 289.15,
    'temp_max': 289.33,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 51,
    'temp_kf': 0.18},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.18, 'deg': 249, 'gust': 3.63},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-03 15:00:00'},
  {'dt': 1772560800,
   'main': {'temp': 283.66,
    'feels_like': 282.33,
    'temp_min': 280.78,
    'temp_max': 283.66,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 60,
    'temp_kf': 2.88},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 11},
   'wind': {'speed': 1.75, 'deg': 292, 'gust': 1.72},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-03 18:00:00'},
  {'dt': 1772571600,
   'main': {'temp': 277.54,
    'feels_like': 276.09,
    'temp_min': 277.54,
    'temp_max': 277.54,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 82,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 15},
   'wind': {'speed': 1.75, 'deg': 323, 'gust': 1.89},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-03 21:00:00'},
  {'dt': 1772582400,
   'main': {'temp': 275.61,
    'feels_like': 273.22,
    'temp_min': 275.61,
    'temp_max': 275.61,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 90,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 16},
   'wind': {'speed': 2.32, 'deg': 5, 'gust': 5.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-04 00:00:00'},
  {'dt': 1772593200,
   'main': {'temp': 278.87,
    'feels_like': 277.23,
    'temp_min': 278.87,
    'temp_max': 278.87,
    'pressure': 1028,
    'sea_level': 1028,
    'grnd_level': 1022,
    'humidity': 91,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 15},
   'wind': {'speed': 2.13, 'deg': 4, 'gust': 4.62},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-04 03:00:00'},
  {'dt': 1772604000,
   'main': {'temp': 277.67,
    'feels_like': 276.16,
    'temp_min': 277.67,
    'temp_max': 277.67,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 86,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 12},
   'wind': {'speed': 1.82, 'deg': 4, 'gust': 3.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-04 06:00:00'},
  {'dt': 1772614800,
   'main': {'temp': 280.12,
    'feels_like': 278.61,
    'temp_min': 280.12,
    'temp_max': 280.12,
    'pressure': 1030,
    'sea_level': 1030,
    'grnd_level': 1024,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 18},
   'wind': {'speed': 2.22, 'deg': 350, 'gust': 3.17},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-04 09:00:00'},
  {'dt': 1772625600,
   'main': {'temp': 283.24,
    'feels_like': 281.22,
    'temp_min': 283.24,
    'temp_max': 283.24,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1024,
    'humidity': 35,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 9},
   'wind': {'speed': 2.33, 'deg': 342, 'gust': 3.09},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-04 12:00:00'},
  {'dt': 1772636400,
   'main': {'temp': 283.91,
    'feels_like': 281.93,
    'temp_min': 283.91,
    'temp_max': 283.91,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 34,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 2.23, 'deg': 342, 'gust': 2.71},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-04 15:00:00'},
  {'dt': 1772647200,
   'main': {'temp': 280.99,
    'feels_like': 280.44,
    'temp_min': 280.99,
    'temp_max': 280.99,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 48,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 1.41, 'deg': 341, 'gust': 1.44},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-04 18:00:00'},
  {'dt': 1772658000,
   'main': {'temp': 279.19,
    'feels_like': 278.49,
    'temp_min': 279.19,
    'temp_max': 279.19,
    'pressure': 1030,
    'sea_level': 1030,
    'grnd_level': 1024,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 1.34, 'deg': 8, 'gust': 1.34},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-04 21:00:00'},
  {'dt': 1772668800,
   'main': {'temp': 277.97,
    'feels_like': 277.97,
    'temp_min': 277.97,
    'temp_max': 277.97,
    'pressure': 1030,
    'sea_level': 1030,
    'grnd_level': 1024,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 1},
   'wind': {'speed': 0.81, 'deg': 57, 'gust': 0.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-05 00:00:00'},
  {'dt': 1772679600,
   'main': {'temp': 277.08,
    'feels_like': 277.08,
    'temp_min': 277.08,
    'temp_max': 277.08,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 65,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 1.31, 'deg': 126, 'gust': 1.32},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-05 03:00:00'},
  {'dt': 1772690400,
   'main': {'temp': 276.21,
    'feels_like': 274.58,
    'temp_min': 276.21,
    'temp_max': 276.21,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 1.73, 'deg': 135, 'gust': 1.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-05 06:00:00'},
  {'dt': 1772701200,
   'main': {'temp': 280.2,
    'feels_like': 278.58,
    'temp_min': 280.2,
    'temp_max': 280.2,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 50,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 16},
   'wind': {'speed': 2.37, 'deg': 120, 'gust': 3.5},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-05 09:00:00'},
  {'dt': 1772712000,
   'main': {'temp': 284.29,
    'feels_like': 282.43,
    'temp_min': 284.29,
    'temp_max': 284.29,
    'pressure': 1028,
    'sea_level': 1028,
    'grnd_level': 1022,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02d'}],
   'clouds': {'all': 19},
   'wind': {'speed': 2.41, 'deg': 130, 'gust': 3.34},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-05 12:00:00'},
  {'dt': 1772722800,
   'main': {'temp': 285.22,
    'feels_like': 283.42,
    'temp_min': 285.22,
    'temp_max': 285.22,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 36,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.49, 'deg': 124, 'gust': 3.29},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-05 15:00:00'},
  {'dt': 1772733600,
   'main': {'temp': 281.53,
    'feels_like': 279.77,
    'temp_min': 281.53,
    'temp_max': 281.53,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.92, 'deg': 104, 'gust': 6.49},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-05 18:00:00'},
  {'dt': 1772744400,
   'main': {'temp': 279.5,
    'feels_like': 277.46,
    'temp_min': 279.5,
    'temp_max': 279.5,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.75, 'deg': 116, 'gust': 6.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-05 21:00:00'},
  {'dt': 1772755200,
   'main': {'temp': 278.07,
    'feels_like': 275.88,
    'temp_min': 278.07,
    'temp_max': 278.07,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 68,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 3},
   'wind': {'speed': 2.59, 'deg': 117, 'gust': 6.42},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-06 00:00:00'},
  {'dt': 1772766000,
   'main': {'temp': 277.13,
    'feels_like': 274.71,
    'temp_min': 277.13,
    'temp_max': 277.13,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 72,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 4},
   'wind': {'speed': 2.65, 'deg': 109, 'gust': 6.67},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-06 03:00:00'},
  {'dt': 1772776800,
   'main': {'temp': 276.6,
    'feels_like': 273.83,
    'temp_min': 276.6,
    'temp_max': 276.6,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 2},
   'wind': {'speed': 2.95, 'deg': 107, 'gust': 7.84},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-06 06:00:00'},
  {'dt': 1772787600,
   'main': {'temp': 281.12,
    'feels_like': 278.82,
    'temp_min': 281.12,
    'temp_max': 281.12,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.68, 'deg': 118, 'gust': 6.71},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-06 09:00:00'},
  {'dt': 1772798400,
   'main': {'temp': 285.79,
    'feels_like': 284.05,
    'temp_min': 285.79,
    'temp_max': 285.79,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 36,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.58, 'deg': 124, 'gust': 5.05},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-06 12:00:00'},
  {'dt': 1772809200,
   'main': {'temp': 286.47,
    'feels_like': 284.82,
    'temp_min': 286.47,
    'temp_max': 286.47,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 37,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 0},
   'wind': {'speed': 3.36, 'deg': 121, 'gust': 4.8},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-06 15:00:00'},
  {'dt': 1772820000,
   'main': {'temp': 282.69,
    'feels_like': 281.05,
    'temp_min': 282.69,
    'temp_max': 282.69,
    'pressure': 1025,
    'sea_level': 1025,
    'grnd_level': 1019,
    'humidity': 52,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 12},
   'wind': {'speed': 3.1, 'deg': 110, 'gust': 7.81},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-06 18:00:00'},
  {'dt': 1772830800,
   'main': {'temp': 280.5,
    'feels_like': 278.7,
    'temp_min': 280.5,
    'temp_max': 280.5,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 34},
   'wind': {'speed': 2.68, 'deg': 118, 'gust': 6.42},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-06 21:00:00'},
  {'dt': 1772841600,
   'main': {'temp': 279.21,
    'feels_like': 277.42,
    'temp_min': 279.21,
    'temp_max': 279.21,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 63,
    'temp_kf': 0},
   'weather': [{'id': 801,
     'main': 'Clouds',
     'description': 'few clouds',
     'icon': '02n'}],
   'clouds': {'all': 23},
   'wind': {'speed': 2.36, 'deg': 119, 'gust': 5.21},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-07 00:00:00'},
  {'dt': 1772852400,
   'main': {'temp': 278.38,
    'feels_like': 276.52,
    'temp_min': 278.38,
    'temp_max': 278.38,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1020,
    'humidity': 67,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01n'}],
   'clouds': {'all': 5},
   'wind': {'speed': 2.28, 'deg': 120, 'gust': 4.12},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-07 03:00:00'},
  {'dt': 1772863200,
   'main': {'temp': 277.81,
    'feels_like': 276.04,
    'temp_min': 277.81,
    'temp_max': 277.81,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 73,
    'temp_kf': 0},
   'weather': [{'id': 800,
     'main': 'Clear',
     'description': 'clear sky',
     'icon': '01d'}],
   'clouds': {'all': 6},
   'wind': {'speed': 2.08, 'deg': 135, 'gust': 3.51},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-07 06:00:00'},
  {'dt': 1772874000,
   'main': {'temp': 282.59,
    'feels_like': 281.35,
    'temp_min': 282.59,
    'temp_max': 282.59,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 59,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 38},
   'wind': {'speed': 2.44, 'deg': 138, 'gust': 4.2},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-07 09:00:00'},
  {'dt': 1772884800,
   'main': {'temp': 287.33,
    'feels_like': 285.98,
    'temp_min': 287.33,
    'temp_max': 287.33,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1021,
    'humidity': 45,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 48},
   'wind': {'speed': 2.67, 'deg': 153, 'gust': 4.07},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-07 12:00:00'},
  {'dt': 1772895600,
   'main': {'temp': 288.06,
    'feels_like': 286.62,
    'temp_min': 288.06,
    'temp_max': 288.06,
    'pressure': 1026,
    'sea_level': 1026,
    'grnd_level': 1021,
    'humidity': 39,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 41},
   'wind': {'speed': 2.72, 'deg': 125, 'gust': 3.5},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-07 15:00:00'},
  {'dt': 1772906400,
   'main': {'temp': 283.85,
    'feels_like': 282.39,
    'temp_min': 283.85,
    'temp_max': 283.85,
    'pressure': 1027,
    'sea_level': 1027,
    'grnd_level': 1022,
    'humidity': 54,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03n'}],
   'clouds': {'all': 41},
   'wind': {'speed': 2.22, 'deg': 97, 'gust': 3.77},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-07 18:00:00'},
  {'dt': 1772917200,
   'main': {'temp': 281.89,
    'feels_like': 280.8,
    'temp_min': 281.89,
    'temp_max': 281.89,
    'pressure': 1028,
    'sea_level': 1028,
    'grnd_level': 1022,
    'humidity': 62,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 77},
   'wind': {'speed': 2.09, 'deg': 115, 'gust': 2.83},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-07 21:00:00'},
  {'dt': 1772928000,
   'main': {'temp': 280.65,
    'feels_like': 279.55,
    'temp_min': 280.65,
    'temp_max': 280.65,
    'pressure': 1028,
    'sea_level': 1028,
    'grnd_level': 1023,
    'humidity': 66,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 67},
   'wind': {'speed': 1.87, 'deg': 113, 'gust': 1.86},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-08 00:00:00'},
  {'dt': 1772938800,
   'main': {'temp': 279.78,
    'feels_like': 278.41,
    'temp_min': 279.78,
    'temp_max': 279.78,
    'pressure': 1028,
    'sea_level': 1028,
    'grnd_level': 1023,
    'humidity': 70,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04n'}],
   'clouds': {'all': 57},
   'wind': {'speed': 2.01, 'deg': 108, 'gust': 1.97},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'n'},
   'dt_txt': '2026-03-08 03:00:00'},
  {'dt': 1772949600,
   'main': {'temp': 278.97,
    'feels_like': 277.28,
    'temp_min': 278.97,
    'temp_max': 278.97,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1023,
    'humidity': 75,
    'temp_kf': 0},
   'weather': [{'id': 802,
     'main': 'Clouds',
     'description': 'scattered clouds',
     'icon': '03d'}],
   'clouds': {'all': 46},
   'wind': {'speed': 2.2, 'deg': 122, 'gust': 3.41},
   'visibility': 10000,
   'pop': 0,
   'sys': {'pod': 'd'},
   'dt_txt': '2026-03-08 06:00:00'},
  {'dt': 1772960400,
   'main': {'temp': 283.52,
    'feels_like': 282.1,
    'temp_min': 283.52,
    'temp_max': 283.52,
    'pressure': 1029,
    'sea_level': 1029,
    'grnd_level': 1024,
    'humidity': 57,
    'temp_kf': 0},
   'weather': [{'id': 803,
     'main': 'Clouds',
     'description': 'broken clouds',
     'icon': '04d'}],
   'clouds': {'all': 73},

Let's access a few values from the JSON.

In [13]:
# Which are the keys?
weather_json.keys()

dict_keys(['cod', 'message', 'cnt', 'list', 'city'])

In [14]:
# What is the value of the list key?
weather_json["list"]

[{'dt': 1772550000,
  'main': {'temp': 289.33,
   'feels_like': 288.34,
   'temp_min': 289.15,
   'temp_max': 289.33,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 51,
   'temp_kf': 0.18},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 5},
  'wind': {'speed': 2.18, 'deg': 249, 'gust': 3.63},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-03 15:00:00'},
 {'dt': 1772560800,
  'main': {'temp': 283.66,
   'feels_like': 282.33,
   'temp_min': 280.78,
   'temp_max': 283.66,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1021,
   'humidity': 60,
   'temp_kf': 2.88},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 11},
  'wind': {'speed': 1.75, 'deg': 292, 'gust': 1.72},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-03 18:00:00'},
 {'dt': 1772571600,
  'main': {'temp': 277.54,
   'feels_like': 276.09,
   'temp_min': 277.54,
   'temp_max': 277.54,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1022,
   'humidity': 82,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 15},
  'wind': {'speed': 1.75, 'deg': 323, 'gust': 1.89},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-03 21:00:00'},
 {'dt': 1772582400,
  'main': {'temp': 275.61,
   'feels_like': 273.22,
   'temp_min': 275.61,
   'temp_max': 275.61,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 90,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 16},
  'wind': {'speed': 2.32, 'deg': 5, 'gust': 5.62},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-04 00:00:00'},
 {'dt': 1772593200,
  'main': {'temp': 278.87,
   'feels_like': 277.23,
   'temp_min': 278.87,
   'temp_max': 278.87,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1022,
   'humidity': 91,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 15},
  'wind': {'speed': 2.13, 'deg': 4, 'gust': 4.62},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-04 03:00:00'},
 {'dt': 1772604000,
  'main': {'temp': 277.67,
   'feels_like': 276.16,
   'temp_min': 277.67,
   'temp_max': 277.67,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 86,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 12},
  'wind': {'speed': 1.82, 'deg': 4, 'gust': 3.83},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-04 06:00:00'},
 {'dt': 1772614800,
  'main': {'temp': 280.12,
   'feels_like': 278.61,
   'temp_min': 280.12,
   'temp_max': 280.12,
   'pressure': 1030,
   'sea_level': 1030,
   'grnd_level': 1024,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 18},
  'wind': {'speed': 2.22, 'deg': 350, 'gust': 3.17},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-04 09:00:00'},
 {'dt': 1772625600,
  'main': {'temp': 283.24,
   'feels_like': 281.22,
   'temp_min': 283.24,
   'temp_max': 283.24,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1024,
   'humidity': 35,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 9},
  'wind': {'speed': 2.33, 'deg': 342, 'gust': 3.09},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-04 12:00:00'},
 {'dt': 1772636400,
  'main': {'temp': 283.91,
   'feels_like': 281.93,
   'temp_min': 283.91,
   'temp_max': 283.91,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 34,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 2.23, 'deg': 342, 'gust': 2.71},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-04 15:00:00'},
 {'dt': 1772647200,
  'main': {'temp': 280.99,
   'feels_like': 280.44,
   'temp_min': 280.99,
   'temp_max': 280.99,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 48,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 3},
  'wind': {'speed': 1.41, 'deg': 341, 'gust': 1.44},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-04 18:00:00'},
 {'dt': 1772658000,
  'main': {'temp': 279.19,
   'feels_like': 278.49,
   'temp_min': 279.19,
   'temp_max': 279.19,
   'pressure': 1030,
   'sea_level': 1030,
   'grnd_level': 1024,
   'humidity': 57,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 1.34, 'deg': 8, 'gust': 1.34},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-04 21:00:00'},
 {'dt': 1772668800,
  'main': {'temp': 277.97,
   'feels_like': 277.97,
   'temp_min': 277.97,
   'temp_max': 277.97,
   'pressure': 1030,
   'sea_level': 1030,
   'grnd_level': 1024,
   'humidity': 62,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 1},
  'wind': {'speed': 0.81, 'deg': 57, 'gust': 0.83},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-05 00:00:00'},
 {'dt': 1772679600,
  'main': {'temp': 277.08,
   'feels_like': 277.08,
   'temp_min': 277.08,
   'temp_max': 277.08,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 65,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 3},
  'wind': {'speed': 1.31, 'deg': 126, 'gust': 1.32},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-05 03:00:00'},
 {'dt': 1772690400,
  'main': {'temp': 276.21,
   'feels_like': 274.58,
   'temp_min': 276.21,
   'temp_max': 276.21,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 67,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 5},
  'wind': {'speed': 1.73, 'deg': 135, 'gust': 1.8},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-05 06:00:00'},
 {'dt': 1772701200,
  'main': {'temp': 280.2,
   'feels_like': 278.58,
   'temp_min': 280.2,
   'temp_max': 280.2,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 50,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 16},
  'wind': {'speed': 2.37, 'deg': 120, 'gust': 3.5},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-05 09:00:00'},
 {'dt': 1772712000,
  'main': {'temp': 284.29,
   'feels_like': 282.43,
   'temp_min': 284.29,
   'temp_max': 284.29,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1022,
   'humidity': 37,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02d'}],
  'clouds': {'all': 19},
  'wind': {'speed': 2.41, 'deg': 130, 'gust': 3.34},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-05 12:00:00'},
 {'dt': 1772722800,
  'main': {'temp': 285.22,
   'feels_like': 283.42,
   'temp_min': 285.22,
   'temp_max': 285.22,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 36,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 5},
  'wind': {'speed': 2.49, 'deg': 124, 'gust': 3.29},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-05 15:00:00'},
 {'dt': 1772733600,
  'main': {'temp': 281.53,
   'feels_like': 279.77,
   'temp_min': 281.53,
   'temp_max': 281.53,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1021,
   'humidity': 54,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 5},
  'wind': {'speed': 2.92, 'deg': 104, 'gust': 6.49},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-05 18:00:00'},
 {'dt': 1772744400,
  'main': {'temp': 279.5,
   'feels_like': 277.46,
   'temp_min': 279.5,
   'temp_max': 279.5,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1021,
   'humidity': 62,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 2},
  'wind': {'speed': 2.75, 'deg': 116, 'gust': 6.8},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-05 21:00:00'},
 {'dt': 1772755200,
  'main': {'temp': 278.07,
   'feels_like': 275.88,
   'temp_min': 278.07,
   'temp_max': 278.07,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 68,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 3},
  'wind': {'speed': 2.59, 'deg': 117, 'gust': 6.42},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-06 00:00:00'},
 {'dt': 1772766000,
  'main': {'temp': 277.13,
   'feels_like': 274.71,
   'temp_min': 277.13,
   'temp_max': 277.13,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 72,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 4},
  'wind': {'speed': 2.65, 'deg': 109, 'gust': 6.67},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-06 03:00:00'},
 {'dt': 1772776800,
  'main': {'temp': 276.6,
   'feels_like': 273.83,
   'temp_min': 276.6,
   'temp_max': 276.6,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 75,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 2},
  'wind': {'speed': 2.95, 'deg': 107, 'gust': 7.84},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-06 06:00:00'},
 {'dt': 1772787600,
  'main': {'temp': 281.12,
   'feels_like': 278.82,
   'temp_min': 281.12,
   'temp_max': 281.12,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 54,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.68, 'deg': 118, 'gust': 6.71},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-06 09:00:00'},
 {'dt': 1772798400,
  'main': {'temp': 285.79,
   'feels_like': 284.05,
   'temp_min': 285.79,
   'temp_max': 285.79,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 36,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.58, 'deg': 124, 'gust': 5.05},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-06 12:00:00'},
 {'dt': 1772809200,
  'main': {'temp': 286.47,
   'feels_like': 284.82,
   'temp_min': 286.47,
   'temp_max': 286.47,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 37,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 0},
  'wind': {'speed': 3.36, 'deg': 121, 'gust': 4.8},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-06 15:00:00'},
 {'dt': 1772820000,
  'main': {'temp': 282.69,
   'feels_like': 281.05,
   'temp_min': 282.69,
   'temp_max': 282.69,
   'pressure': 1025,
   'sea_level': 1025,
   'grnd_level': 1019,
   'humidity': 52,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 12},
  'wind': {'speed': 3.1, 'deg': 110, 'gust': 7.81},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-06 18:00:00'},
 {'dt': 1772830800,
  'main': {'temp': 280.5,
   'feels_like': 278.7,
   'temp_min': 280.5,
   'temp_max': 280.5,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 57,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 34},
  'wind': {'speed': 2.68, 'deg': 118, 'gust': 6.42},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-06 21:00:00'},
 {'dt': 1772841600,
  'main': {'temp': 279.21,
   'feels_like': 277.42,
   'temp_min': 279.21,
   'temp_max': 279.21,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 63,
   'temp_kf': 0},
  'weather': [{'id': 801,
    'main': 'Clouds',
    'description': 'few clouds',
    'icon': '02n'}],
  'clouds': {'all': 23},
  'wind': {'speed': 2.36, 'deg': 119, 'gust': 5.21},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-07 00:00:00'},
 {'dt': 1772852400,
  'main': {'temp': 278.38,
   'feels_like': 276.52,
   'temp_min': 278.38,
   'temp_max': 278.38,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1020,
   'humidity': 67,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01n'}],
  'clouds': {'all': 5},
  'wind': {'speed': 2.28, 'deg': 120, 'gust': 4.12},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-07 03:00:00'},
 {'dt': 1772863200,
  'main': {'temp': 277.81,
   'feels_like': 276.04,
   'temp_min': 277.81,
   'temp_max': 277.81,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 73,
   'temp_kf': 0},
  'weather': [{'id': 800,
    'main': 'Clear',
    'description': 'clear sky',
    'icon': '01d'}],
  'clouds': {'all': 6},
  'wind': {'speed': 2.08, 'deg': 135, 'gust': 3.51},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-07 06:00:00'},
 {'dt': 1772874000,
  'main': {'temp': 282.59,
   'feels_like': 281.35,
   'temp_min': 282.59,
   'temp_max': 282.59,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 59,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 38},
  'wind': {'speed': 2.44, 'deg': 138, 'gust': 4.2},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-07 09:00:00'},
 {'dt': 1772884800,
  'main': {'temp': 287.33,
   'feels_like': 285.98,
   'temp_min': 287.33,
   'temp_max': 287.33,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1021,
   'humidity': 45,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 48},
  'wind': {'speed': 2.67, 'deg': 153, 'gust': 4.07},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-07 12:00:00'},
 {'dt': 1772895600,
  'main': {'temp': 288.06,
   'feels_like': 286.62,
   'temp_min': 288.06,
   'temp_max': 288.06,
   'pressure': 1026,
   'sea_level': 1026,
   'grnd_level': 1021,
   'humidity': 39,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 41},
  'wind': {'speed': 2.72, 'deg': 125, 'gust': 3.5},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-07 15:00:00'},
 {'dt': 1772906400,
  'main': {'temp': 283.85,
   'feels_like': 282.39,
   'temp_min': 283.85,
   'temp_max': 283.85,
   'pressure': 1027,
   'sea_level': 1027,
   'grnd_level': 1022,
   'humidity': 54,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03n'}],
  'clouds': {'all': 41},
  'wind': {'speed': 2.22, 'deg': 97, 'gust': 3.77},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-07 18:00:00'},
 {'dt': 1772917200,
  'main': {'temp': 281.89,
   'feels_like': 280.8,
   'temp_min': 281.89,
   'temp_max': 281.89,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1022,
   'humidity': 62,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 77},
  'wind': {'speed': 2.09, 'deg': 115, 'gust': 2.83},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-07 21:00:00'},
 {'dt': 1772928000,
  'main': {'temp': 280.65,
   'feels_like': 279.55,
   'temp_min': 280.65,
   'temp_max': 280.65,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1023,
   'humidity': 66,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 67},
  'wind': {'speed': 1.87, 'deg': 113, 'gust': 1.86},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-08 00:00:00'},
 {'dt': 1772938800,
  'main': {'temp': 279.78,
   'feels_like': 278.41,
   'temp_min': 279.78,
   'temp_max': 279.78,
   'pressure': 1028,
   'sea_level': 1028,
   'grnd_level': 1023,
   'humidity': 70,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04n'}],
  'clouds': {'all': 57},
  'wind': {'speed': 2.01, 'deg': 108, 'gust': 1.97},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'n'},
  'dt_txt': '2026-03-08 03:00:00'},
 {'dt': 1772949600,
  'main': {'temp': 278.97,
   'feels_like': 277.28,
   'temp_min': 278.97,
   'temp_max': 278.97,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 75,
   'temp_kf': 0},
  'weather': [{'id': 802,
    'main': 'Clouds',
    'description': 'scattered clouds',
    'icon': '03d'}],
  'clouds': {'all': 46},
  'wind': {'speed': 2.2, 'deg': 122, 'gust': 3.41},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-08 06:00:00'},
 {'dt': 1772960400,
  'main': {'temp': 283.52,
   'feels_like': 282.1,
   'temp_min': 283.52,
   'temp_max': 283.52,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1024,
   'humidity': 57,
   'temp_kf': 0},
  'weather': [{'id': 803,
    'main': 'Clouds',
    'description': 'broken clouds',
    'icon': '04d'}],
  'clouds': {'all': 73},
  'wind': {'speed': 2.34, 'deg': 134, 'gust': 3.89},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-08 09:00:00'},
 {'dt': 1772971200,
  'main': {'temp': 287.9,
   'feels_like': 286.42,
   'temp_min': 287.9,
   'temp_max': 287.9,
   'pressure': 1029,
   'sea_level': 1029,
   'grnd_level': 1023,
   'humidity': 38,
   'temp_kf': 0},
  'weather': [{'id': 804,
    'main': 'Clouds',
    'description': 'overcast clouds',
    'icon': '04d'}],
  'clouds': {'all': 85},
  'wind': {'speed': 2.46, 'deg': 147, 'gust': 3.88},
  'visibility': 10000,
  'pop': 0,
  'sys': {'pod': 'd'},
  'dt_txt': '2026-03-08 12:00:00'}]

In [15]:
# What is the wind?
# [0] refers to the first 3-hour block in the forecast
wind_speed = weather_json["list"][0]["wind"]["speed"]
print(f"Wind Speed: {wind_speed} m/s")

Wind Speed: 2.18 m/s

## 2.  Transforming a JSON into a DataFrame

🚲 What’s useful for E-Scooter Users?
* *dt_txt*: data about date
* *main.temp*: data about temperature
* *main.feels_like*: how the temperature feels like. The "RealFeel" tells them if they need gloves to avoid numb fingers
* *wind.speed*: data about wind's speed
* *wind.gust*: more critical than speed. A 14.47 m/s gust (found in Feb 21 data) can easily knock a standing rider off balance. 
* *visibility*: your data shows a drop to 5299m during rain. Lower visibility means a higher risk of not being seen by cars
* *weather.main*: clouds, rain etc.
* *weather.description*: clouds, rain etc. and description
* *pop (Probability of Precipitation)*: this is the #1 "Abandon Trip" metric. If pop > 0.5, users will likely switch to public transport
* *rain*: crucial for safety. 
* *snow*: crucial for safety. Even 0.31mm of snow makes city tiles and metal manhole covers lethal for thin scooter tires

In [16]:
# Flatten the JSON
weather_df = pd.json_normalize(weather_json['list'])

# Extract nested list data (the 'weather' column is a list)
weather_df['weather.main'] = weather_df['weather'].str[0].str.get('main')
weather_df['weather.description'] = weather_df['weather'].str[0].str.get('description')

# List every useful column in final table
target_cols = [
    'dt_txt', 'main.temp', 'main.feels_like', 'wind.speed',
    'wind.gust', 'visibility', 'weather.main',
    'weather.description', 'pop', 'rain', 'snow'
]

# Create clean_df. fill_value=0 handles missing rain/snow keys automatically.
clean_df = weather_df.reindex(columns=target_cols, fill_value=0)

#Final cleanup: replace any NaNs within existing columns with 0
clean_df = clean_df.fillna(0)

clean_df

,dt_txt,main.temp,main.feels_like,wind.speed,wind.gust,visibility,weather.main,weather.description,pop,rain,snow
0,2026-03-03 15:00:00,289.33,288.34,2.18,3.63,10000,Clear,clear sky,0,0,0
1,2026-03-03 18:00:00,283.66,282.33,1.75,1.72,10000,Clouds,few clouds,0,0,0
2,2026-03-03 21:00:00,277.54,276.09,1.75,1.89,10000,Clouds,few clouds,0,0,0
3,2026-03-04 00:00:00,275.61,273.22,2.32,5.62,10000,Clouds,few clouds,0,0,0
4,2026-03-04 03:00:00,278.87,277.23,2.13,4.62,10000,Clouds,few clouds,0,0,0
5,2026-03-04 06:00:00,277.67,276.16,1.82,3.83,10000,Clouds,few clouds,0,0,0
6,2026-03-04 09:00:00,280.12,278.61,2.22,3.17,10000,Clouds,few clouds,0,0,0
7,2026-03-04 12:00:00,283.24,281.22,2.33,3.09,10000,Clear,clear sky,0,0,0
8,2026-03-04 15:00:00,283.91,281.93,2.23,2.71,10000,Clear,clear sky,0,0,0
9,2026-03-04 18:00:00,280.99,280.44,1.41,1.44,10000,Clear,clear sky,0,0,0
10,2026-03-04 21:00:00,279.19,278.49,1.34,1.34,10000,Clear,clear sky,0,0,0
11,2026-03-05 00:00:00,277.97,277.97,0.81,0.83,10000,Clear,clear sky,0,0,0
12,2026-03-05 03:00:00,277.08,277.08,1.31,1.32,10000,Clear,clear sky,0,0,0
13,2026-03-05 06:00:00,276.21,274.58,1.73,1.80,10000,Clear,clear sky,0,0,0
14,2026-03-05 09:00:00,280.20,278.58,2.37,3.50,10000,Clouds,few clouds,0,0,0
15,2026-03-05 12:00:00,284.29,282.43,2.41,3.34,10000,Clouds,few clouds,0,0,0
16,2026-03-05 15:00:00,285.22,283.42,2.49,3.29,10000,Clear,clear sky,0,0,0
17,2026-03-05 18:00:00,281.53,279.77,2.92,6.49,10000,Clear,clear sky,0,0,0
18,2026-03-05 21:00:00,279.50,277.46,2.75,6.80,10000,Clear,clear sky,0,0,0
19,2026-03-06 00:00:00,278.07,275.88,2.59,6.42,10000,Clear,clear sky,0,0,0
20,2026-03-06 03:00:00,277.13,274.71,2.65,6.67,10000,Clear,clear sky,0,0,0
21,2026-03-06 06:00:00,276.60,273.83,2.95,7.84,10000,Clear,clear sky,0,0,0
22,2026-03-06 09:00:00,281.12,278.82,3.68,6.71,10000,Clear,clear sky,0,0,0
23,2026-03-06 12:00:00,285.79,284.05,3.58,5.05,10000,Clear,clear sky,0,0,0
24,2026-03-06 15:00:00,286.47,284.82,3.36,4.80,10000,Clear,clear sky,0,0,0
25,2026-03-06 18:00:00,282.69,281.05,3.10,7.81,10000,Clouds,few clouds,0,0,0
26,2026-03-06 21:00:00,280.50,278.70,2.68,6.42,10000,Clouds,scattered clouds,0,0,0
27,2026-03-07 00:00:00,279.21,277.42,2.36,5.21,10000,Clouds,few clouds,0,0,0
28,2026-03-07 03:00:00,278.38,276.52,2.28,4.12,10000,Clear,clear sky,0,0,0
29,2026-03-07 06:00:00,277.81,276.04,2.08,3.51,10000,Clear,clear sky,0,0,0
30,2026-03-07 09:00:00,282.59,281.35,2.44,4.20,10000,Clouds,scattered clouds,0,0,0
31,2026-03-07 12:00:00,287.33,285.98,2.67,4.07,10000,Clouds,scattered clouds,0,0,0
32,2026-03-07 15:00:00,288.06,286.62,2.72,3.50,10000,Clouds,scattered clouds,0,0,0
33,2026-03-07 18:00:00,283.85,282.39,2.22,3.77,10000,Clouds,scattered clouds,0,0,0
34,2026-03-07 21:00:00,281.89,280.80,2.09,2.83,10000,Clouds,broken clouds,0,0,0
35,2026-03-08 00:00:00,280.65,279.55,1.87,1.86,10000,Clouds,broken clouds,0,0,0
36,2026-03-08 03:00:00,279.78,278.41,2.01,1.97,10000,Clouds,broken clouds,0,0,0
37,2026-03-08 06:00:00,278.97,277.28,2.20,3.41,10000,Clouds,scattered clouds,0,0,0
38,2026-03-08 09:00:00,283.52,282.10,2.34,3.89,10000,Clouds,broken clouds,0,0,0
39,2026-03-08 12:00:00,287.90,286.42,2.46,3.88,10000,Clouds,overcast clouds,0,0,0

In [17]:
# Transform JSON into a DataFrame. Option #2
weather_df = pd.DataFrame(weather_json['list'])
weather_df

,dt,main,weather,clouds,wind,visibility,pop,sys,dt_txt
0,1772550000,"{'temp': 289.33, 'feels_like': 288.34, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 5},"{'speed': 2.18, 'deg': 249, 'gust': 3.63}",10000,0,{'pod': 'd'},2026-03-03 15:00:00
1,1772560800,"{'temp': 283.66, 'feels_like': 282.33, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 11},"{'speed': 1.75, 'deg': 292, 'gust': 1.72}",10000,0,{'pod': 'n'},2026-03-03 18:00:00
2,1772571600,"{'temp': 277.54, 'feels_like': 276.09, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 15},"{'speed': 1.75, 'deg': 323, 'gust': 1.89}",10000,0,{'pod': 'n'},2026-03-03 21:00:00
3,1772582400,"{'temp': 275.61, 'feels_like': 273.22, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 16},"{'speed': 2.32, 'deg': 5, 'gust': 5.62}",10000,0,{'pod': 'n'},2026-03-04 00:00:00
4,1772593200,"{'temp': 278.87, 'feels_like': 277.23, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 15},"{'speed': 2.13, 'deg': 4, 'gust': 4.62}",10000,0,{'pod': 'n'},2026-03-04 03:00:00
5,1772604000,"{'temp': 277.67, 'feels_like': 276.16, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 12},"{'speed': 1.82, 'deg': 4, 'gust': 3.83}",10000,0,{'pod': 'd'},2026-03-04 06:00:00
6,1772614800,"{'temp': 280.12, 'feels_like': 278.61, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 18},"{'speed': 2.22, 'deg': 350, 'gust': 3.17}",10000,0,{'pod': 'd'},2026-03-04 09:00:00
7,1772625600,"{'temp': 283.24, 'feels_like': 281.22, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 9},"{'speed': 2.33, 'deg': 342, 'gust': 3.09}",10000,0,{'pod': 'd'},2026-03-04 12:00:00
8,1772636400,"{'temp': 283.91, 'feels_like': 281.93, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 0},"{'speed': 2.23, 'deg': 342, 'gust': 2.71}",10000,0,{'pod': 'd'},2026-03-04 15:00:00
9,1772647200,"{'temp': 280.99, 'feels_like': 280.44, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 3},"{'speed': 1.41, 'deg': 341, 'gust': 1.44}",10000,0,{'pod': 'n'},2026-03-04 18:00:00
10,1772658000,"{'temp': 279.19, 'feels_like': 278.49, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 2},"{'speed': 1.34, 'deg': 8, 'gust': 1.34}",10000,0,{'pod': 'n'},2026-03-04 21:00:00
11,1772668800,"{'temp': 277.97, 'feels_like': 277.97, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 1},"{'speed': 0.81, 'deg': 57, 'gust': 0.83}",10000,0,{'pod': 'n'},2026-03-05 00:00:00
12,1772679600,"{'temp': 277.08, 'feels_like': 277.08, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 3},"{'speed': 1.31, 'deg': 126, 'gust': 1.32}",10000,0,{'pod': 'n'},2026-03-05 03:00:00
13,1772690400,"{'temp': 276.21, 'feels_like': 274.58, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 5},"{'speed': 1.73, 'deg': 135, 'gust': 1.8}",10000,0,{'pod': 'd'},2026-03-05 06:00:00
14,1772701200,"{'temp': 280.2, 'feels_like': 278.58, 'temp_mi...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 16},"{'speed': 2.37, 'deg': 120, 'gust': 3.5}",10000,0,{'pod': 'd'},2026-03-05 09:00:00
15,1772712000,"{'temp': 284.29, 'feels_like': 282.43, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 19},"{'speed': 2.41, 'deg': 130, 'gust': 3.34}",10000,0,{'pod': 'd'},2026-03-05 12:00:00
16,1772722800,"{'temp': 285.22, 'feels_like': 283.42, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 5},"{'speed': 2.49, 'deg': 124, 'gust': 3.29}",10000,0,{'pod': 'd'},2026-03-05 15:00:00
17,1772733600,"{'temp': 281.53, 'feels_like': 279.77, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 5},"{'speed': 2.92, 'deg': 104, 'gust': 6.49}",10000,0,{'pod': 'n'},2026-03-05 18:00:00
18,1772744400,"{'temp': 279.5, 'feels_like': 277.46, 'temp_mi...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 2},"{'speed': 2.75, 'deg': 116, 'gust': 6.8}",10000,0,{'pod': 'n'},2026-03-05 21:00:00
19,1772755200,"{'temp': 278.07, 'feels_like': 275.88, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 3},"{'speed': 2.59, 'deg': 117, 'gust': 6.42}",10000,0,{'pod': 'n'},2026-03-06 00:00:00
20,1772766000,"{'temp': 277.13, 'feels_like': 274.71, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 4},"{'speed': 2.65, 'deg': 109, 'gust': 6.67}",10000,0,{'pod': 'n'},2026-03-06 03:00:00
21,1772776800,"{'temp': 276.6, 'feels_like': 273.83, 'temp_mi...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 2},"{'speed': 2.95, 'deg': 107, 'gust': 7.84}",10000,0,{'pod': 'd'},2026-03-06 06:00:00
22,1772787600,"{'temp': 281.12, 'feels_like': 278.82, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 0},"{'speed': 3.68, 'deg': 118, 'gust': 6.71}",10000,0,{'pod': 'd'},2026-03-06 09:00:00
23,1772798400,"{'temp': 285.79, 'feels_like': 284.05, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 0},"{'speed': 3.58, 'deg': 124, 'gust': 5.05}",10000,0,{'pod': 'd'},2026-03-06 12:00:00
24,1772809200,"{'temp': 286.47, 'feels_like': 284.82, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 0},"{'speed': 3.36, 'deg': 121, 'gust': 4.8}",10000,0,{'pod': 'd'},2026-03-06 15:00:00
25,1772820000,"{'temp': 282.69, 'feels_like': 281.05, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 12},"{'speed': 3.1, 'deg': 110, 'gust': 7.81}",10000,0,{'pod': 'n'},2026-03-06 18:00:00
26,1772830800,"{'temp': 280.5, 'feels_like': 278.7, 'temp_min...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 34},"{'speed': 2.68, 'deg': 118, 'gust': 6.42}",10000,0,{'pod': 'n'},2026-03-06 21:00:00
27,1772841600,"{'temp': 279.21, 'feels_like': 277.42, 'temp_m...","[{'id': 801, 'main': 'Clouds', 'description': ...",{'all': 23},"{'speed': 2.36, 'deg': 119, 'gust': 5.21}",10000,0,{'pod': 'n'},2026-03-07 00:00:00
28,1772852400,"{'temp': 278.38, 'feels_like': 276.52, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 5},"{'speed': 2.28, 'deg': 120, 'gust': 4.12}",10000,0,{'pod': 'n'},2026-03-07 03:00:00
29,1772863200,"{'temp': 277.81, 'feels_like': 276.04, 'temp_m...","[{'id': 800, 'main': 'Clear', 'description': '...",{'all': 6},"{'speed': 2.08, 'deg': 135, 'gust': 3.51}",10000,0,{'pod': 'd'},2026-03-07 06:00:00
30,1772874000,"{'temp': 282.59, 'feels_like': 281.35, 'temp_m...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 38},"{'speed': 2.44, 'deg': 138, 'gust': 4.2}",10000,0,{'pod': 'd'},2026-03-07 09:00:00
31,1772884800,"{'temp': 287.33, 'feels_like': 285.98, 'temp_m...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 48},"{'speed': 2.67, 'deg': 153, 'gust': 4.07}",10000,0,{'pod': 'd'},2026-03-07 12:00:00
32,1772895600,"{'temp': 288.06, 'feels_like': 286.62, 'temp_m...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 41},"{'speed': 2.72, 'deg': 125, 'gust': 3.5}",10000,0,{'pod': 'd'},2026-03-07 15:00:00
33,1772906400,"{'temp': 283.85, 'feels_like': 282.39, 'temp_m...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 41},"{'speed': 2.22, 'deg': 97, 'gust': 3.77}",10000,0,{'pod': 'n'},2026-03-07 18:00:00
34,1772917200,"{'temp': 281.89, 'feels_like': 280.8, 'temp_mi...","[{'id': 803, 'main': 'Clouds', 'description': ...",{'all': 77},"{'speed': 2.09, 'deg': 115, 'gust': 2.83}",10000,0,{'pod': 'n'},2026-03-07 21:00:00
35,1772928000,"{'temp': 280.65, 'feels_like': 279.55, 'temp_m...","[{'id': 803, 'main': 'Clouds', 'description': ...",{'all': 67},"{'speed': 1.87, 'deg': 113, 'gust': 1.86}",10000,0,{'pod': 'n'},2026-03-08 00:00:00
36,1772938800,"{'temp': 279.78, 'feels_like': 278.41, 'temp_m...","[{'id': 803, 'main': 'Clouds', 'description': ...",{'all': 57},"{'speed': 2.01, 'deg': 108, 'gust': 1.97}",10000,0,{'pod': 'n'},2026-03-08 03:00:00
37,1772949600,"{'temp': 278.97, 'feels_like': 277.28, 'temp_m...","[{'id': 802, 'main': 'Clouds', 'description': ...",{'all': 46},"{'speed': 2.2, 'deg': 122, 'gust': 3.41}",10000,0,{'pod': 'd'},2026-03-08 06:00:00
38,1772960400,"{'temp': 283.52, 'feels_like': 282.1, 'temp_mi...","[{'id': 803, 'main': 'Clouds', 'description': ...",{'all': 73},"{'speed': 2.34, 'deg': 134, 'gust': 3.89}",10000,0,{'pod': 'd'},2026-03-08 09:00:00
39,1772971200,"{'temp': 287.9, 'feels_like': 286.42, 'temp_mi...","[{'id': 804, 'main': 'Clouds', 'description': ...",{'all': 85},"{'speed': 2.46, 'deg': 147, 'gust': 3.88}",10000,0,{'pod': 'd'},2026-03-08 12:00:00

## 3. Create a function for 3 cities

In [18]:
cities = ['Berlin', 'Hamburg', 'Munich']
country = 'Germany'
API_key = os.getenv("API_key")
weather_data = []
# Combine the different parts from above to create one url

for city in cities:
    # Geocoding: get lat/lon for any city/country
    geo_url = f"http://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=1&appid={API_key}"
    geo_response = requests.get(geo_url, timeout=5)

    if geo_response.status_code == 200 and geo_response.json():
        geo_data = geo_response.json()[0]
        lat, lon = geo_data['lat'], geo_data['lon']

        # Get weather using a specific lat/lon
        weather_url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}&units=metric"
        weather_response = requests.get(weather_url, timeout=5)

        if weather_response.status_code == 200:
            weather_json = weather_response.json()

        # Transform JSON into DataFrame
        temp_df = pd.json_normalize(weather_json['list'])
        temp_df['city'] = city

        # Extract nested list data (the 'weather' column is a list)
        temp_df['weather.main'] = temp_df['weather'].str[0].str.get('main')
        temp_df['weather.description'] = temp_df['weather'].str[0].str.get('description')

        weather_data.append(temp_df)

# Combine all cities into one DataFrame
if weather_data:
     weather_df = pd.concat(weather_data, ignore_index=True)
    # Handle Rain and Snow (OpenWeather uses 'rain.3h' and 'snow.3h')
target_cols = ['city',
    'dt_txt', 'main.temp', 'main.feels_like', 'wind.speed',
    'wind.gust', 'visibility', 'weather.main',
    'weather.description', 'pop', 'rain', 'snow'
]
    # Create clean_df. fill_value=0 handles missing rain/snow keys automatically
clean_df = weather_df.reindex(columns=target_cols, fill_value=0).fillna(0)
clean_df
print(clean_df.to_string())

        city               dt_txt  main.temp  main.feels_like  wind.speed  wind.gust  visibility weather.main weather.description  pop  rain  snow
0     Berlin  2026-03-03 15:00:00      16.10            15.07        2.18       3.63       10000        Clear           clear sky    0     0     0
1     Berlin  2026-03-03 18:00:00      10.27             8.97        1.75       1.72       10000       Clouds          few clouds    0     0     0
2     Berlin  2026-03-03 21:00:00       4.39             2.94        1.75       1.89       10000       Clouds          few clouds    0     0     0
3     Berlin  2026-03-04 00:00:00       2.46             0.07        2.32       5.62       10000       Clouds          few clouds    0     0     0
4     Berlin  2026-03-04 03:00:00       5.72             4.08        2.13       4.62       10000       Clouds          few clouds    0     0     0
5     Berlin  2026-03-04 06:00:00       4.52             3.01        1.82       3.83       10000       Clouds          few clouds    0     0     0
6     Berlin  2026-03-04 09:00:00       6.97             5.46        2.22       3.17       10000       Clouds          few clouds    0     0     0
7     Berlin  2026-03-04 12:00:00      10.09             8.07        2.33       3.09       10000        Clear           clear sky    0     0     0
8     Berlin  2026-03-04 15:00:00      10.76             8.78        2.23       2.71       10000        Clear           clear sky    0     0     0
9     Berlin  2026-03-04 18:00:00       7.84             7.29        1.41       1.44       10000        Clear           clear sky    0     0     0
10    Berlin  2026-03-04 21:00:00       6.04             5.34        1.34       1.34       10000        Clear           clear sky    0     0     0
11    Berlin  2026-03-05 00:00:00       4.82             4.82        0.81       0.83       10000        Clear           clear sky    0     0     0
12    Berlin  2026-03-05 03:00:00       3.93             3.93        1.31       1.32       10000        Clear           clear sky    0     0     0
13    Berlin  2026-03-05 06:00:00       3.06             1.43        1.73       1.80       10000        Clear           clear sky    0     0     0
14    Berlin  2026-03-05 09:00:00       7.05             5.43        2.37       3.50       10000       Clouds          few clouds    0     0     0
15    Berlin  2026-03-05 12:00:00      11.14             9.28        2.41       3.34       10000       Clouds          few clouds    0     0     0
16    Berlin  2026-03-05 15:00:00      12.07            10.27        2.49       3.29       10000        Clear           clear sky    0     0     0
17    Berlin  2026-03-05 18:00:00       8.38             6.62        2.92       6.49       10000        Clear           clear sky    0     0     0
18    Berlin  2026-03-05 21:00:00       6.35             4.31        2.75       6.80       10000        Clear           clear sky    0     0     0
19    Berlin  2026-03-06 00:00:00       4.92             2.73        2.59       6.42       10000        Clear           clear sky    0     0     0
20    Berlin  2026-03-06 03:00:00       3.98             1.56        2.65       6.67       10000        Clear           clear sky    0     0     0
21    Berlin  2026-03-06 06:00:00       3.45             0.68        2.95       7.84       10000        Clear           clear sky    0     0     0
22    Berlin  2026-03-06 09:00:00       7.97             5.67        3.68       6.71       10000        Clear           clear sky    0     0     0
23    Berlin  2026-03-06 12:00:00      12.64            10.90        3.58       5.05       10000        Clear           clear sky    0     0     0
24    Berlin  2026-03-06 15:00:00      13.32            11.67        3.36       4.80       10000        Clear           clear sky    0     0     0
25    Berlin  2026-03-06 18:00:00       9.54             7.90        3.10       7.81       10000       Clouds          few clouds    0     0     0
26    Berlin  2026-03-06 21:00:00       7.35             5.55        2.68       6.42       10000       Clouds    scattered clouds    0     0     0
27    Berlin  2026-03-07 00:00:00       6.06             4.27        2.36       5.21       10000       Clouds          few clouds    0     0     0
28    Berlin  2026-03-07 03:00:00       5.23             3.37        2.28       4.12       10000        Clear           clear sky    0     0     0
29    Berlin  2026-03-07 06:00:00       4.66             2.89        2.08       3.51       10000        Clear           clear sky    0     0     0
30    Berlin  2026-03-07 09:00:00       9.44             8.20        2.44       4.20       10000       Clouds    scattered clouds    0     0     0
31    Berlin  2026-03-07 12:00:00      14.18            12.83        2.67       4.07       10000       Clouds    scattered clouds    0     0     0
32    Berlin  2026-03-07 15:00:00      14.91            13.47        2.72       3.50       10000       Clouds    scattered clouds    0     0     0
33    Berlin  2026-03-07 18:00:00      10.70             9.24        2.22       3.77       10000       Clouds    scattered clouds    0     0     0
34    Berlin  2026-03-07 21:00:00       8.74             7.65        2.09       2.83       10000       Clouds       broken clouds    0     0     0
35    Berlin  2026-03-08 00:00:00       7.50             6.40        1.87       1.86       10000       Clouds       broken clouds    0     0     0
36    Berlin  2026-03-08 03:00:00       6.63             5.26        2.01       1.97       10000       Clouds       broken clouds    0     0     0
37    Berlin  2026-03-08 06:00:00       5.82             4.13        2.20       3.41       10000       Clouds    scattered clouds    0     0     0
38    Berlin  2026-03-08 09:00:00      10.37             8.95        2.34       3.89       10000       Clouds       broken clouds    0     0     0
39    Berlin  2026-03-08 12:00:00      14.75            13.27        2.46       3.88       10000       Clouds     overcast clouds    0     0     0
40   Hamburg  2026-03-03 15:00:00      15.14            14.25        3.28       4.74       10000       Clouds    scattered clouds    0     0     0
41   Hamburg  2026-03-03 18:00:00      11.08            10.28        2.36       5.86       10000       Clouds    scattered clouds    0     0     0
42   Hamburg  2026-03-03 21:00:00       6.23             4.29        2.59       7.80       10000        Clear           clear sky    0     0     0
43   Hamburg  2026-03-04 00:00:00       4.69             3.07        1.94       5.25       10000       Clouds          few clouds    0     0     0
44   Hamburg  2026-03-04 03:00:00       2.37             0.71        1.67       1.59       10000       Clouds       broken clouds    0     0     0
45   Hamburg  2026-03-04 06:00:00       1.02             1.02        1.31       1.35       10000       Clouds    scattered clouds    0     0     0
46   Hamburg  2026-03-04 09:00:00       5.84             5.84        1.04       1.71       10000        Clear           clear sky    0     0     0
47   Hamburg  2026-03-04 12:00:00       9.70             9.70        0.91       1.13       10000        Clear           clear sky    0     0     0
48   Hamburg  2026-03-04 15:00:00       9.91             9.65        1.40       1.62       10000        Clear           clear sky    0     0     0
49   Hamburg  2026-03-04 18:00:00       5.22             4.20        1.50       1.43       10000        Clear           clear sky    0     0     0
50   Hamburg  2026-03-04 21:00:00       3.52             1.68        1.97       1.91       10000        Clear           clear sky    0     0     0
51   Hamburg  2026-03-05 00:00:00       2.37            -0.01        2.29       3.35       10000        Clear           clear sky    0     0     0
52   Hamburg  2026-03-05 03:00:00       1.83            -0.69        2.33       4.66       10000        Clear           clear sky    0     0     0
53   Hamburg  2026-03-05 06:00:00       1.66            -1.14        2.59       5.79       10000        Clear           clear sky    0     0     0
54   Hamburg  2026-03-05 09:00:00       7.09             4.90        3.18       6.77       10000        Clear           clear sky    0     0     0
55   Hamburg  2026-03-05 12:00:00      11.83            10.53        3.84       5.62       10000        Clear           clear sky    0     0     0
56   Hamburg  2026-03-05 15:00:00      12.18            10.92        3.46       6.43       10000        Clear           clear sky    0     0     0
57   Hamburg  2026-03-05 18:00:00       6.77             4.77        2.80       7.98       10000        Clear           clear sky    0     0     0
58   Hamburg  2026-03-05 21:00:00       5.17             3.07        2.54       6.34       10000        Clear           clear sky    0     0     0
59   Hamburg  2026-03-06 00:00:00       4.21             1.89        2.59       6.74       10000        Clear           clear sky    0     0     0
60   Hamburg  2026-03-06 03:00:00       3.32             0.81        2.61       6.57       10000        Clear           clear sky    0     0     0
61   Hamburg  2026-03-06 06:00:00       2.40            -0.40        2.74       7.19       10000        Clear           clear sky    0     0     0
62   Hamburg  2026-03-06 09:00:00       7.57             5.26        3.54       7.16       10000        Clear           clear sky    0     0     0
63   Hamburg  2026-03-06 12:00:00      12.49            11.00        3.75       5.84       10000        Clear           clear sky    0     0     0
64   Hamburg  2026-03-06 15:00:00      12.76            11.48        2.79       5.27       10000       Clouds          few clouds    0     0     0
65   Hamburg  2026-03-06 18:00:00       7.39             5.95        2.23       2.93       10000       Clouds    scattered clouds    0     0     0
66   Hamburg  2026-03-06 21:00:00       5.82             4.21        2.12       2.67       10000       Clouds       broken clouds    0     0     0
67   Hamburg  2026-03-07 00:00:00       4.94             3.46        1.85       1.77       10000       Clouds       broken clouds    0     0     0
68   Hamburg  2026-03-07 03:00:00       4.41             3.06        1.67       1.65       10000       Clouds       broken clouds    0     0     0
69   Hamburg  2026-03-07 06:00:00       3.95             2.50        1.69       1.66       10000       Clouds     overcast clouds    0     0     0
70   Hamburg  2026-03-07 09:00:00       8.86             8.37        1.48       2.36       10000       Clouds     overcast clouds    0     0     0
71   Hamburg  2026-03-07 12:00:00      12.81            11.53        1.47       1.76       10000       Clouds     overcast clouds    0     0     0
72   Hamburg  2026-03-07 15:00:00      13.15            12.06        1.72       2.75       10000       Clouds     overcast clouds    0     0     0
73   Hamburg  2026-03-07 18:00:00       8.28             7.25        1.93       1.94       10000       Clouds     overcast clouds    0     0     0
74   Hamburg  2026-03-07 21:00:00       6.88             5.93        1.64       1.65       10000       Clouds    scattered clouds    0     0     0
75   Hamburg  2026-03-08 00:00:00       6.23             5.23        1.60       1.59       10000       Clouds       broken clouds    0     0     0
76   Hamburg  2026-03-08 03:00:00       5.62             4.05        2.04       2.27       10000       Clouds     overcast clouds    0     0     0
77   Hamburg  2026-03-08 06:00:00       5.01             3.23        2.15       2.57       10000       Clouds     overcast clouds    0     0     0
78   Hamburg  2026-03-08 09:00:00      10.12             9.02        2.44       4.54       10000       Clouds       broken clouds    0     0     0
79   Hamburg  2026-03-08 12:00:00      14.49            13.43        2.87       4.34       10000       Clouds       broken clouds    0     0     0
80    Munich  2026-03-03 15:00:00      11.05            10.12        1.88       1.51       10000       Clouds       broken clouds    0     0     0
81    Munich  2026-03-03 18:00:00       7.97             7.51        1.35       1.48       10000       Clouds    scattered clouds    0     0     0
82    Munich  2026-03-03 21:00:00       2.89             2.89        0.86       0.91       10000        Clear           clear sky    0     0     0
83    Munich  2026-03-04 00:00:00       1.94             1.94        0.84       0.93       10000        Clear           clear sky    0     0     0
84    Munich  2026-03-04 03:00:00       3.95             3.95        0.88       0.83       10000        Clear           clear sky    0     0     0
85    Munich  2026-03-04 06:00:00       3.25             3.25        0.87       0.76       10000        Clear           clear sky    0     0     0
86    Munich  2026-03-04 09:00:00       8.26             8.26        0.15       0.25       10000        Clear           clear sky    0     0     0
87    Munich  2026-03-04 12:00:00      11.70            10.47        1.57       1.22       10000        Clear           clear sky    0     0     0
88    Munich  2026-03-04 15:00:00      11.93            10.59        2.16       2.00       10000       Clouds    scattered clouds    0     0     0
89    Munich  2026-03-04 18:00:00       7.59             6.26        2.14       3.24       10000       Clouds    scattered clouds    0     0     0
90    Munich  2026-03-04 21:00:00       5.86             4.12        2.27       4.97       10000        Clear           clear sky    0     0     0
91    Munich  2026-03-05 00:00:00       4.78             2.86        2.25       5.33       10000        Clear           clear sky    0     0     0
92    Munich  2026-03-05 03:00:00       3.81             1.83        2.14       4.15       10000        Clear           clear sky    0     0     0
93    Munich  2026-03-05 06:00:00       2.93             0.50        2.45       6.74       10000        Clear           clear sky    0     0     0
94    Munich  2026-03-05 09:00:00       8.27             5.87        4.02       7.22       10000        Clear           clear sky    0     0     0
95    Munich  2026-03-05 12:00:00      12.58            11.20        4.62       6.36       10000        Clear           clear sky    0     0     0
96    Munich  2026-03-05 15:00:00      12.76            11.50        4.14       5.84       10000        Clear           clear sky    0     0     0
97    Munich  2026-03-05 18:00:00       7.50             5.59        2.88       8.98       10000        Clear           clear sky    0     0     0
98    Munich  2026-03-05 21:00:00       5.78             4.29        1.99       4.15       10000        Clear           clear sky    0     0     0
99    Munich  2026-03-06 00:00:00       4.60             3.16        1.77       2.34       10000       Clouds          few clouds    0     0     0
100   Munich  2026-03-06 03:00:00       3.96             2.72        1.53       1.52       10000        Clear           clear sky    0     0     0
101   Munich  2026-03-06 06:00:00       3.13             1.65        1.62       1.98       10000        Clear           clear sky    0     0     0
102   Munich  2026-03-06 09:00:00       8.84             7.45        2.50       4.01       10000        Clear           clear sky    0     0     0
103   Munich  2026-03-06 12:00:00      13.00            11.63        3.52       4.29       10000        Clear           clear sky    0     0     0
104   Munich  2026-03-06 15:00:00      13.24            11.98        3.37       4.47       10000       Clouds          few clouds    0     0     0
105   Munich  2026-03-06 18:00:00       7.74             6.46        2.11       3.41       10000       Clouds          few clouds    0     0     0
106   Munich  2026-03-06 21:00:00       6.02             6.02        0.99       1.14       10000       Clouds    scattered clouds    0     0     0
107   Munich  2026-03-07 00:00:00       5.11             5.11        0.29       0.76       10000       Clouds    scattered clouds    0     0     0
108   Munich  2026-03-07 03:00:00       4.35             4.35        0.45       0.76       10000       Clouds       broken clouds    0     0     0
109   Munich  2026-03-07 06:00:00       3.71             3.71        0.69       0.68       10000       Clouds       broken clouds    0     0     0
110   Munich  2026-03-07 09:00:00       9.32             9.32        0.40       0.30       10000        Clear           clear sky    0     0     0
111   Munich  2026-03-07 12:00:00      13.51            12.33        1.24       0.63       10000        Clear           clear sky    0     0     0
112   Munich  2026-03-07 15:00:00      13.78            12.62        1.53       1.31       10000        Clear           clear sky    0     0     0
113   Munich  2026-03-07 18:00:00       9.10             8.46        1.66       1.91       10000        Clear           clear sky    0     0     0
114   Munich  2026-03-07 21:00:00       7.27             7.27        1.19       1.24       10000        Clear           clear sky    0     0     0
115   Munich  2026-03-08 00:00:00       6.16             6.16        0.42       0.62       10000        Clear           clear sky    0     0     0
116   Munich  2026-03-08 03:00:00       5.21             5.21        0.80       0.72       10000        Clear           clear sky    0     0     0
117   Munich  2026-03-08 06:00:00       4.63             4.63        1.11       1.09       10000        Clear           clear sky    0     0     0
118   Munich  2026-03-08 09:00:00      10.21             9.09        0.18       0.19       10000       Clouds    scattered clouds    0     0     0
119   Munich  2026-03-08 12:00:00      13.65            12.53        1.85       1.35       10000       Clouds    scattered clouds    0     0     0

Create a function to get weather for defined cities.

In [19]:
def get_weather_forecast(cities, country, api_key):
    weather_data = []

    for city in cities:
        # geocoding
        geo_url = f"http://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=1&appid={api_key}"
        geo_response = requests.get(geo_url, timeout=5)

        if geo_response.status_code == 200 and geo_response.json():
            geo_data = geo_response.json()[0]
            lat, lon = geo_data['lat'], geo_data['lon']

            # weather Forecast
            weather_url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={api_key}&units=metric"
            weather_response = requests.get(weather_url, timeout=5)

            if weather_response.status_code == 200:
                weather_json = weather_response.json()

                # transform
                temp_df = pd.json_normalize(weather_json['list'])
                temp_df['city'] = city
                temp_df['weather.main'] = temp_df['weather'].str[0].str.get('main')
                temp_df['weather.description'] = temp_df['weather'].str[0].str.get('description')

                weather_data.append(temp_df)

    # combine and clean
    if not weather_data:
        return pd.DataFrame() # Return empty DF if no data found

    weather_df = pd.concat(weather_data, ignore_index=True)

    target_cols = [
        'city', 'dt_txt', 'main.temp', 'main.feels_like', 'wind.speed',
        'wind.gust', 'visibility', 'weather.main',
        'weather.description', 'pop', 'rain', 'snow'
    ]

    return weather_df.reindex(columns=target_cols, fill_value=0).fillna(0)

# --- How to use the function ---
my_cities = ['Berlin', 'Hamburg', 'Munich']
my_key = os.getenv("API_key")

final_weather_df = get_weather_forecast(my_cities, 'Germany', my_key)
final_weather_df

,city,dt_txt,main.temp,main.feels_like,wind.speed,wind.gust,visibility,weather.main,weather.description,pop,rain,snow
0,Berlin,2026-03-03 15:00:00,16.10,15.07,2.18,3.63,10000,Clear,clear sky,0,0,0
1,Berlin,2026-03-03 18:00:00,10.27,8.97,1.75,1.72,10000,Clouds,few clouds,0,0,0
2,Berlin,2026-03-03 21:00:00,4.39,2.94,1.75,1.89,10000,Clouds,few clouds,0,0,0
3,Berlin,2026-03-04 00:00:00,2.46,0.07,2.32,5.62,10000,Clouds,few clouds,0,0,0
4,Berlin,2026-03-04 03:00:00,5.72,4.08,2.13,4.62,10000,Clouds,few clouds,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
115,Munich,2026-03-08 00:00:00,6.16,6.16,0.42,0.62,10000,Clear,clear sky,0,0,0
116,Munich,2026-03-08 03:00:00,5.21,5.21,0.80,0.72,10000,Clear,clear sky,0,0,0
117,Munich,2026-03-08 06:00:00,4.63,4.63,1.11,1.09,10000,Clear,clear sky,0,0,0
118,Munich,2026-03-08 09:00:00,10.21,9.09,0.18,0.19,10000,Clouds,scattered clouds,0,0,0
119,Munich,2026-03-08 12:00:00,13.65,12.53,1.85,1.35,10000,Clouds,scattered clouds,0,0,0

Rename the columns in our DataFrame:

In [20]:
# Define a dictionary mapping the old names to new names
column_mapping = {
    'city': 'city',
    'dt_txt': 'forecast_time',
    'main.temp': 'temperature',
    'main.feels_like': 'feels_like',
    'wind.speed': 'wind_speed',
    'wind.gust': 'wind_gust',
    'visibility': 'visibility',
    'weather.main': 'weather',
    'weather.description': 'description_',
    'pop': 'precipitation_prob',
    'rain.3h': 'rain',
    'snow.3h': 'snow'
       }

# Apply the rename
weathers_df = clean_df.rename(columns=column_mapping)

# View the final result
weathers_df

,city,forecast_time,temperature,feels_like,wind_speed,wind_gust,visibility,weather,description_,precipitation_prob,rain,snow
0,Berlin,2026-03-03 15:00:00,16.10,15.07,2.18,3.63,10000,Clear,clear sky,0,0,0
1,Berlin,2026-03-03 18:00:00,10.27,8.97,1.75,1.72,10000,Clouds,few clouds,0,0,0
2,Berlin,2026-03-03 21:00:00,4.39,2.94,1.75,1.89,10000,Clouds,few clouds,0,0,0
3,Berlin,2026-03-04 00:00:00,2.46,0.07,2.32,5.62,10000,Clouds,few clouds,0,0,0
4,Berlin,2026-03-04 03:00:00,5.72,4.08,2.13,4.62,10000,Clouds,few clouds,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
115,Munich,2026-03-08 00:00:00,6.16,6.16,0.42,0.62,10000,Clear,clear sky,0,0,0
116,Munich,2026-03-08 03:00:00,5.21,5.21,0.80,0.72,10000,Clear,clear sky,0,0,0
117,Munich,2026-03-08 06:00:00,4.63,4.63,1.11,1.09,10000,Clear,clear sky,0,0,0
118,Munich,2026-03-08 09:00:00,10.21,9.09,0.18,0.19,10000,Clouds,scattered clouds,0,0,0
119,Munich,2026-03-08 12:00:00,13.65,12.53,1.85,1.35,10000,Clouds,scattered clouds,0,0,0

## 4. Retrieving our DataFrame to SQL

In [21]:
# configuration and connection
schema = "sql_gans"
host = "127.0.0.1"
user = "root"
password = os.getenv("password")
port = 3306

if password is None:
    raise ValueError("ERROR: 'password' not found in .env file. Check your filename and path.")

# build connection string only if password exists
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'
print("Connection string created successfully.")

Connection string created successfully.

Merging our weather DataFrame with `cities` table.

In [22]:
from sqlalchemy import create_engine
# fetch the city_ids from MySQL 'cities' table
engine = create_engine(connection_string)
cities_from_sql = pd.read_sql_table('cities', con=engine)
final_to_sql = (
    weathers_df
    .merge(cities_from_sql[['city_id', 'city']], on='city', how='left')
)

Create the function to send data from our DataFrame to `weathers` table into MySQL

In [23]:
def send_weather_to_sql(weathers_df, engine):
        # create engine inside the function

        # update the list: 'city_id' instead of 'city'
        sql_columns = [
                'city_id', 'forecast_time', 'temperature', 'feels_like',
                'wind_speed', 'wind_gust', 'visibility', 'weather', 'description_',
                'precipitation_prob', 'rain', 'snow'
        ]

        try:
          data_to_send = weathers_df[sql_columns]
          data_to_send.to_sql(
            name='weathers',      # specify the SQL table name here
            con=engine,           # database connection
            if_exists='append',   # add data to existing table
            index=False           # do not write the DataFrame index as a column
            )
          print(f"Success! {len(data_to_send)} rows synced to SQL.")

        except KeyError as e:
          print(f"Error: Your DataFrame is missing a column: {e}")
        except Exception as e:
          print(f"SQL Error: {e}")
send_weather_to_sql(final_to_sql, engine)

Success! 120 rows synced to SQL.

Create a function which fetching data from `cities` table in MySQL, call weather API and send data to MySQL (into `weathers` table)

In [24]:
# configuration and connection
schema = "sql_gans"
host = "127.0.0.1"
user = "root"
password = os.getenv("password")
port = 3306

if password is None:
    raise ValueError("ERROR: 'password' not found in .env file. Check your filename and path.")

# build connection string only if password exists
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'
print("Connection string created successfully.")

Connection string created successfully.

In [25]:
import pandas as pd
import requests
import os
from sqlalchemy import create_engine

def get_weather_forecast(connection_string, API_key):
    engine = create_engine(connection_string)

    # fetch City Data
    cities_df = pd.read_sql("SELECT city_id, city, country FROM cities", con=engine)
    print(f"--- Found {len(cities_df)} cities in SQL table ---")

    if cities_df.empty:
        print("Error: Your 'cities' table is empty!")
        return

    weather_data = []

    for _, row in cities_df.iterrows():
        city = row['city']
        country = row['country']
        city_id = row['city_id']
        print(f"Processing: {city}, {country}...")

        # geocoding URL path
        geo_url = f"http://api.openweathermap.org/geo/1.0/direct?q={city},{country}&limit=1&appid={API_key}"
        geo_response = requests.get(geo_url)

        if geo_response.status_code != 200:
            print(f"API Error {geo_response.status_code}: {geo_response.text}")
            continue
        geo_data = geo_response.json()
        # safe access to list elements
        if geo_data and isinstance(geo_data, list) and len(geo_data) > 0:
            lat = geo_data[0]['lat']
            lon = geo_data[0]['lon']

            # weather URL path
            weather_url = f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_key}&units=metric"
            weather_response = requests.get(weather_url).json()

            if 'list' in weather_response:
                temp_df = pd.json_normalize(weather_response['list'])
                temp_df['city_id'] = city_id

                # unpack nested weather description safely
                temp_df['weather.main'] = temp_df['weather'].str[0].str.get('main')
                temp_df['weather.description'] = temp_df['weather'].str[0].str.get('description')

                weather_data.append(temp_df)
                print(f"Success for {city}")
            else:
                print(f"Forecast failed for {city}: {weather_response.get('message', 'No message')}")
        else:
            print(f"Geocoding failed: Could not find coordinates for '{city}'")

    if not weather_data:
        print("No weather data found.")
        return

    full_df = pd.concat(weather_data, ignore_index=True)

    column_mapping = {
        'dt_txt': 'forecast_time',
        'main.temp': 'temperature',
        'main.feels_like': 'feels_like',
        'wind.speed': 'wind_speed',
        'wind.gust': 'wind_gust',
        'visibility': 'visibility',
        'weather.main': 'weather',
        'weather.description': 'description_',
        'pop': 'precipitation_prob',
        'rain.3h': 'rain',
        'snow.3h': 'snow'
    }

    # prevent KeyError if rain/snow columns are missing from the API response
    final_df = (
        full_df.reindex(columns=list(column_mapping.keys()) + ['city_id'], fill_value=0)
        .rename(columns=column_mapping)
        .fillna(0)
    )

    final_df.to_sql(name='weathers', con=engine, if_exists='append', index=False)
    print(f"Successfully updated weather for {len(weather_data)} cities.")

# --- Execution ---
API_key = os.getenv("API_key")
# (Your connection_string logic here...)
# configuration and connection
schema = "sql_gans"
host = "127.0.0.1"
user = "root"
password = os.getenv("password")
port = 3306

if password is None:
    raise ValueError("ERROR: 'password' not found in .env file. Check your filename and path.")

# build connection string only if password exists
connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'
print("Connection string created successfully.")

get_weather_forecast(connection_string, API_key)

Connection string created successfully.
--- Found 3 cities in SQL table ---
Processing: Berlin, Germany...
Success for Berlin
Processing: Hamburg, Germany...
Success for Hamburg
Processing: Munich, Germany...
Success for Munich
Successfully updated weather for 3 cities.